[package]
authors = ["Philipp Korber <p.korber@1aim.com>"]
categories = []
description = "TODO"
keywords = ["mail", "codec", "mime", "smtp"]
license = "MIT OR Apache-2.0"
name = "mail-codec"
readme = "./README.md"
repository = "https://github.com/dathinab/mail-codec"
version = "0.1.0"

[badges]

[badges.travis-ci]
branch = "master"
repository = "dathinab/mail-codec"

[dependencies]
ascii = "0.8.4"
base64 = "0.6.0"
chrono = "0.4.0"
error-chain = "0.10.0"
futures = "0.1.14"
mime = "0.3.2"
nom = "3.1.0"
owning_ref = "0.3.3"
quoted_printable = "0.3.0"
rand = "0.3.15"
scoped-tls = "0.1.0"
serde = "1.0.10"
serde_derive = "1.0.10"

[dependencies.futures-cpupool]
optional = true
version = "0.1.5"

[dev-dependencies]
serde_json = "1.0.2"

[features]
default = ["default_impl"]
default_impl = ["default_impl_mail", "default_impl_compose"]
default_impl_any = []
default_impl_component_id = ["default_impl_any"]
default_impl_compose = ["default_impl_name_composer", "default_impl_component_id"]
default_impl_cpupool = ["futures-cpupool", "default_impl_any"]
default_impl_fs = ["default_impl_any"]
default_impl_mail = ["default_impl_cpupool", "default_impl_fs", "default_impl_vfs"]
default_impl_name_composer = ["default_impl_any"]
default_impl_vfs = ["default_impl_any"]
