[package]
authors = ["Philipp Korber <p.korber@1aim.com>"]
name = "mail-codec-core"
description = "TODO"
documentation = "https://docs.rs/mail-codec-core"
keywords = []
categories = []
license = "MIT OR Apache-2.0"
repository = "https://github.com/1aim/mail-codec"
version = "0.0.1"
